[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["ad101-lab <adickhans@gmail.com>"]
description = ""
name = "python-backend"
version = "0.1.0"
[tool.poetry.dependencies]
lists = "^1.3"
python = "^3.7"
[tool.poetry.dev-dependencies]
